In [3]:
list1 = ["ramesh", 34, 5.9 , "unmarried", "chef"]
print(list1)

['ramesh', 34, 5.9, 'unmarried', 'chef']


In [4]:
list1[4]

'chef'

In [5]:
list1[4] = "sales man"

In [6]:
print(list1)

['ramesh', 34, 5.9, 'unmarried', 'sales man']


In [18]:
list1.append("male")
print(list1)

['ramesh', 34, 5.9, 'unmarried', 'sales man', 'Male', 'Male', 'Male', 'Male', 'male', 'male']


In [24]:
list1 = [1,2,3]
list2 = [1,2,3]

list1 = list(range(10))
print(list1)

list2 = [i*2 for i in list1]
print(list2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [25]:
type(list1)

list

In [26]:
type(list2)

list

In [29]:
##Tuples


tup1 = (10,20,30,40, "America", "New york", "True", True)
print(tup1)

(10, 20, 30, 40, 'America', 'New york', 'True', True)


In [30]:
len(tup1)

8

In [31]:
dic1 = {
    "Name": "Ranbir singla",
    "Age": 29,
    "Sex": "Male",
    "Department": "Sales",
    "Position": "Sales excutive",
    "Salary": 65000,
    "Contact": {
        "Email ID": "Ranbir.singla@gmail.com",
        "Contact": 8527445467
    }
}

In [32]:
print(dic1)

{'Name': 'Ranbir singla', 'Age': 29, 'Sex': 'Male', 'Department': 'Sales', 'Position': 'Sales excutive', 'Salary': 65000, 'Contact': {'Email ID': 'Ranbir.singla@gmail.com', 'Contact': 8527445467}}


In [33]:
dic1.keys()

dict_keys(['Name', 'Age', 'Sex', 'Department', 'Position', 'Salary', 'Contact'])

In [34]:
dic1.values()

dict_values(['Ranbir singla', 29, 'Male', 'Sales', 'Sales excutive', 65000, {'Email ID': 'Ranbir.singla@gmail.com', 'Contact': 8527445467}])

In [39]:
dic1["Name"]

'Ranbir singla'

In [ ]:
## Doubt

In [1]:
dic2 = {
    "Name": ["Ranbir singla", "Kavya mehra", "kabir singh"],
    "Age": [29, 34, 32],
    "Sex": ["Male", "Female", "Male"],
    "Department": ["Sales", "management", "Operations"],
    "Position": ["Sales excutive", "Manager", "Operation Coordinator"],
    "Salary": [65000, 75000, 45000],
        "Email ID": ["Ranbir.singla@gmail.com", "Kavya.mehra@gmail.com", "Kabir.ada@gmail.com"],
        "Contact": [8527445467, 9910890282, 8527689335],
    
}
print(dic2)

{'Name': ['Ranbir singla', 'Kavya mehra', 'kabir singh'], 'Age': [29, 34, 32], 'Sex': ['Male', 'Female', 'Male'], 'Department': ['Sales', 'management', 'Operations'], 'Position': ['Sales excutive', 'Manager', 'Operation Coordinator'], 'Salary': [65000, 75000, 45000], 'Email ID': ['Ranbir.singla@gmail.com', 'Kavya.mehra@gmail.com', 'Kabir.ada@gmail.com'], 'Contact': [8527445467, 9910890282, 8527689335]}


In [4]:
import pandas as pd
df2 = pd.DataFrame(dic2)

df2

Name  Age     Sex  Department               Position  Salary  \
0  Ranbir singla   29    Male       Sales         Sales excutive   65000   
1    Kavya mehra   34  Female  management                Manager   75000   
2    kabir singh   32    Male  Operations  Operation Coordinator   45000   

                  Email ID     Contact  
0  Ranbir.singla@gmail.com  8527445467  
1    Kavya.mehra@gmail.com  9910890282  
2      Kabir.ada@gmail.com  8527689335

In [8]:
list5 = [10, 20, 30, 40, 50]
list5*2

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [12]:
import numpy as np

In [13]:
arr1 = np.array([10,20,30,40])
print(arr1)

[10 20 30 40]


In [14]:
arr1*2

array([20, 40, 60, 80])

In [15]:
arr1**2

array([ 100,  400,  900, 1600])

In [17]:
arr10 = np.array([1,2,3,4,5])
arr20 = np.array([6,7,8,9,0])

arr10+arr20

array([ 7,  9, 11, 13,  5])

In [18]:
arr10.shape

(5,)

In [19]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [21]:
a1 = np.linspace(1,20,50)
print(a1)

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]


In [25]:
##Matrix

A = np.array([[1,5,9],
             [2,5,7]])

A

array([[1, 5, 9],
       [2, 5, 7]])

In [26]:
A.shape

(2, 3)

In [33]:
ZERO = np.zeros((4,8))
print(ZERO)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [31]:
zero_matrix = np.zeros((3,7))
print(zero_matrix)

zero_matrix.shape

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


(3, 7)

In [36]:
my_list1 = (1,2,3,4,5,6,7,8,9)
print(my_list1)

(1, 2, 3, 4, 5, 6, 7, 8, 9)


In [39]:
A1 = np.array(my_list1)

A1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
A2 =  [1, 2, 3, [4, 5, 6, [7, 8, 9,]]]

A2

[1, 2, 3, [4, 5, 6, [7, 8, 9]]]

In [53]:
print(A2[3][3][0])  


7


In [57]:
np.random.rand(5)

array([0.78688077, 0.89855916, 0.26462565, 0.73835436, 0.49462719])

In [58]:
np.random.rand(4,8)

array([[0.07801526, 0.075406  , 0.9230402 , 0.92983369, 0.73471267,
        0.92879683, 0.16828815, 0.56167488],
       [0.41512571, 0.49725375, 0.57924963, 0.10975412, 0.28148733,
        0.34749361, 0.57268447, 0.86181474],
       [0.85276633, 0.8162367 , 0.00469057, 0.20010157, 0.8661143 ,
        0.27127207, 0.15809346, 0.11059901],
       [0.84678361, 0.23883578, 0.97496422, 0.43520752, 0.5763678 ,
        0.80320636, 0.64282357, 0.09212732]])

In [59]:
np.random.randint(5,9)

6

In [61]:
np.random.randint(1,30,60)

array([17, 20,  8,  6,  8, 12, 17,  4,  8, 25,  7, 26, 12, 18, 26,  8, 10,
       16,  5, 22, 22, 25, 23,  8, 20,  4, 27, 25, 16, 18,  3, 10, 28, 10,
       23, 27, 25, 12, 29, 15,  7, 28, 28, 13, 11, 24,  7, 20, 15,  6, 23,
       27, 11,  8, 22,  2, 25,  2, 16, 26])

In [62]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [63]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [65]:
np.hstack([x,y])

array([1, 2, 3, 4, 5, 6])

In [68]:
x = np.array([2,5])

x

array([2, 5])

In [76]:
import pandas as pd

In [79]:
detail1 = pd.Series(data = [1,2,3,4], index = ["america", "canadian", "indian", "african"])

print(detail1)

america     1
canadian    2
indian      3
african     4
dtype: int64


In [82]:
detail2 = pd.Series(data = [10,20,30,40], index = ["Brazalian", "Nagerian", "Afgani", "Sri Lankan"])

print(detail2)

Brazalian     10
Nagerian      20
Afgani        30
Sri Lankan    40
dtype: int64


In [86]:
detail2['Sri Lankan']

40

In [87]:
detail1+detail2

Afgani       NaN
Brazalian    NaN
Nagerian     NaN
Sri Lankan   NaN
african      NaN
america      NaN
canadian     NaN
indian       NaN
dtype: float64

In [92]:
## Data frame


print(np.random.rand(4,8))
print(type(np.random.randn(4,8)))

[[0.62709039 0.36667495 0.67645488 0.77896003 0.91019303 0.5569676
  0.92449196 0.51541004]
 [0.76304379 0.95747734 0.53419976 0.3032221  0.33223905 0.59596301
  0.97369616 0.28012941]
 [0.89654679 0.86761968 0.84254345 0.3027445  0.59509896 0.24596452
  0.24852358 0.46687983]
 [0.3153495  0.67903588 0.9714187  0.92441708 0.9779355  0.16872022
  0.87593259 0.03091409]]
<class 'numpy.ndarray'>


In [94]:
DF1 = pd.DataFrame(np.random.rand(4,8))

DF1

0         1         2         3         4         5         6  \
0  0.459399  0.201528  0.583641  0.542345  0.543555  0.383975  0.812344   
1  0.805415  0.110889  0.298022  0.778695  0.918009  0.292746  0.232654   
2  0.290192  0.807064  0.947377  0.385652  0.561529  0.020277  0.669541   
3  0.394633  0.188602  0.436981  0.769779  0.440242  0.904595  0.405481   

          7  
0  0.782264  
1  0.082942  
2  0.733652  
3  0.103914

In [99]:
DF2 = pd.DataFrame(np.random.rand(4,8), index =['A', 'B', 'C', 'D',])

DF2

0         1         2         3         4         5         6  \
A  0.681322  0.348196  0.763141  0.440306  0.475142  0.797604  0.730478   
B  0.254812  0.091183  0.631957  0.015857  0.526303  0.135693  0.700605   
C  0.498661  0.109887  0.475073  0.611075  0.461831  0.797461  0.269076   
D  0.393651  0.442283  0.400546  0.773649  0.303601  0.592196  0.642291   

          7  
A  0.106365  
B  0.915290  
C  0.708147  
D  0.581519

In [104]:
K = "My Name is Kabir Baneshi"
K1 = K.split()

K1

['My', 'Name', 'is', 'Kabir', 'Baneshi']

In [108]:
K = "My_Name_is_Kabir_Baneshi"
K1 = K.split("_")

K1

['My', 'Name', 'is', 'Kabir', 'Baneshi']

In [132]:
Df3 = pd.DataFrame(np.random.rand(4,8),
                   index = ['A', 'B', 'C', 'D',], 
                   coloums = ['2010', '2011', '2012', '2013', '2014', '2015', '2016'].split[])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1800370754.py, line 3)

In [134]:
DF2.shape

(4, 8)